### ISSUE TITLE
Crash on dense ore sprite creation

### ISSUE THREAD

**Issue by pupnewfster** [PersonTheCat/ore_stone_variants#17]
version 2.18
crash report: https://pastebin.com/HNHPHaXK

Steps to reproduce, turn on dense ore creation, remove the resources.zip file and then on the next start the game will crash as the just generated base sprites/overlays do not exist where it is looking for them. Restarting the game after the crash loads normally as the base sprites now exist.

**Comment by PersonTheCat** [comment]
Just to clarify, this problem goes away upon restart?

**Comment by pupnewfster** [comment]
Yes because it successfully creates all the non dense variant sprites.

**Comment by PersonTheCat** [comment]
I see. It is supposed to always check for the textures and create them if they don't exist, but maybe I can fix this by adding a check earlier on or something. I'll look into it soon. 

Thanks!

**Comment by pupnewfster** [comment]
I believe the issue is that it creates them if they do not exist but it does not save them before it then attempts to get the texture after creating it.

**Comment by PersonTheCat** [comment]
So I've been either not experiencing this issue or not following the steps to reproduce it correctly. Regardless, I've rewritten things in a way that I think would circumvent this issue and it is generating the overlays correctly for me with no crashes. Would you mind trying this test build for me when you get the chance?

[ore_stone_variants-2.19.1.zip](https://github.com/PersonTheCat/ore_stone_variants/files/2138931/ore_stone_variants-2.19.1.zip)

**Comment by pupnewfster** [comment]
This worked correctly, thank you.

**Comment by PersonTheCat** [comment]
Cool. There was actually also an issue with ores that had builtin normal overlays but not builtin blended overlays, but I fixed that as well. I'll go ahead and close these issues.

**Comment by pupnewfster** [comment]
This is not actually working correctly as I still crash. I just had not had the mod installed when I did not crash as I by mistake was just using the zip instead of the jar. Look at Edit 3

**Comment by PersonTheCat** [comment]
I'm pretty sure this is the issue I was experiencing where only builtin normal textures were included. All three overlays get generated from one method now, but the blended variant should not generate in that case. I would send you another test build to confirm, but I'm working on Modern Metals support 
at the moment and then I'm gonna take a break.
